---
all:
  children:
    linux_hosts:
      hosts:
        edge-node-1:
          ansible_host: edge-node-1.example.lan
        edge-node-2:
          ansible_host: edge-node-2.example.lan
    linux_hosts_standby:
      hosts:
        edge-node-3:
          ansible_host: edge-node-3.example.lan
