---
all:
  children:
    raspberry_pis:
      hosts:
        edge-node-1:
          ansible_host: edge-node-1.example.lan
        edge-node-2:
          ansible_host: edge-node-2.example.lan
        edge-node-3:
          ansible_host: edge-node-3.example.lan
